### ISSUE TITLE
Kaggle上に公開されているNotebookの参照方法

### ISSUE THREAD

**Issue by mkbc3000** [upura/python-kaggle-start-book#14]
1.5.3 の「2.1節で取り組むNotebookへのアクセス」方法がわかりませんでした。
（Kaggle上に公開されているNotebookがあり、それを元にして「Copy and Edit」することは理解しています）
よろしくお願い致します。

**Comment by upura** [comment]
文中の「2.1節で取り組むNotebook」は、直前に言及がある通り「本書のサンプルコードとして公開されているNotebook」です。本書のサンプルコードは、p.5に記載の通り、本GitHubリポジトリにて公開しています。「[README.md](https://github.com/upura/python-kaggle-start-book/blob/master/README.md#%E5%AF%BE%E5%BF%9C%E3%81%99%E3%82%8Bkaggle%E3%81%AEnotebook)」に明示している「対応するKaggleのNotebook」から、2.1節用の「ch02_01.ipynb」のリンクをクリックしてください。

**Comment by mkbc3000** [comment]
ご回答ありがとうございます。無事該当のNotebookを参照できました。
「README.md」にリンクがあったのですね。
Github、Notebookに不慣れなため、初歩的な質問で失礼致しました。
