### ISSUE TITLE
「2.4.2 仮説から新しい特徴量を作る」の質問

### ISSUE THREAD

**Issue by upura** [upura/python-kaggle-start-book#23]
```
kaggleスタートブックの「2.4.2 仮説から新しい特徴量を作る」で２つ質問させてください。

・FamilySizeのデータを作成するために記載されているコードのようにParchとSibSpを加算した後、sns.countplot・・・を実行したら、Key Error : 'Parch'とエラーになり、初めからやり直したりしてみましたが、解決できません。Parchデータが存在しないからなのでしょうか。

・ ...data['SibSp'] + 1の部分で、1を足しているのは何故ですか？

ご回答よろしくお願いいたします。
```
https://qiita.com/upura/items/3c10ff6fed4e7c3d70f0#comment-71f2d916e3cf8e70e757

1点目について、具体的なコードをご提示いただくのが確実ですが、`sns.countplot`の実行時に`Key Error : 'Parch'`のエラーが出るということは、コードの記述が間違っているように感じます。実行時のxもしくはhueで'Parch'を指定していませんか？

以下はサンプルコード内の該当部分です。

```python
sns.countplot(x='FamilySize', data=train, hue='Survived')
```
https://www.kaggle.com/sishihara/python-kaggle-start-book-ch02-04

2点目について1を足しているのは、家族の人数を表現するためです。p.64, 65で説明している通り、SibSpとParchはそれぞれ「同乗した兄弟姉妹と配偶者の人数」「同乗した親と子供の人数」を意味します。ここに本人分の1を足すことで、家族の人数を表現しています。

**Comment by Muranikofu** [comment]
ご回答ありがとうございます。実行時のxもしくはhueで'Parch'が指定していないか確認しましたが、コードの記述は同じくできていました。改めて、自身がコード記述したものと、エラーを添付させて頂きます。

<img width="735" alt="2020-06-26 (5)" src="https://user-images.githubusercontent.com/64767955/85750769-f556ff80-b744-11ea-82ce-a88a20f817cc.png">

<img width="723" alt="2020-06-26 (6)" src="https://user-images.githubusercontent.com/64767955/85750802-fdaf3a80-b744-11ea-84da-c37ab3c23344.png">

質問2点目の何故1を足すのかの理由も理解することができました。
ありがとうございます。

**Comment by upura** [comment]
スクリーンショットを拝見したところ、`sns.countplot`の実行前の次の行でエラーが出ていますね。原因はdataというpd.DataFrame内に'Parch'というカラムが存在しないことです。

```python
data['FamilySize'] = data['Parch'] + data['SibSp'] + 1
```

前段の処理を確認しないと詳しいところは分かりませんが、恐らくは[サンプルコード](https://www.kaggle.com/sishihara/python-kaggle-start-book-ch02-04)のIn[10]の処理を実施していないことが理由だと思います。

本サンプルコードのIn[5]では、「再現性の大切さ」の話題に取り組む中で、次の処理によって一旦dataからいくつかのカラムを削除しています。

```python
delete_columns = ['Name', 'PassengerId', 'SibSp', 'Parch', 'Ticket', 'Cabin']
data.drop(delete_columns, axis=1, inplace=True)
```

その後に「仮説から新しい特徴量を作る」の話題に移った後には、改めてdataを読み込み直しています。ここで、data内に'Parch'というカラムが復活します。

**Comment by Muranikofu** [comment]
教えて頂きながら、返信が遅くなり大変申し訳ありません。
無事に解決できました。
サンプルコードのIn[10]の処理を失念していました。
ご指摘通り、'Parch'のカラムを削除して、復活しないままコードを実行していたのが、エラーの原因でした。

教えて頂き、ありがとうございました。
