### ISSUE TITLE
submitする時のcsvファイルの保存の方法について

### ISSUE THREAD

**Issue by Muranikofu** [upura/python-kaggle-start-book#24]
教えて頂きたいことがあります。
kaggleスタートブックの【2.2.5 submit】のコードを参考に、submitする時、csvファイルを保存してますが、全く同じscoreとなります。
改めて、確認させて頂きたいです。
例えば、
Optunaで調整したLightGBMでの予測結果
Cross Validationでの予測結果
StratifiedKFoldを用いた際の予測結果
上記の項目について本の順番に従い、各々を予測した後、submitするためにcsvファイルを保存するときのコードは、

sub = pd.read_csv('../input/titanic/gender_submission.csv')
sub['Survived'] = list(map(int, y_pred))
sub.to_csv('submission.csv'（適宜名前を変更）, index=False)

上記の方法でよろしいでしょうか。

出来るだけ詳細に書いたつもりではございますが、分かりにくかったら申し訳ございません。

ご回答よろしくお願いいたします。

**Comment by currypurin** [comment]
submitファイルを作るコードですが、  

- y_predが、0 or 1でのtestデータの予測値になっている場合のcsvの作り方の例として、2.2.5ではそのコードを書いています。 
- 例えば2.7.4の StratifiedKFoldの箇所では、次のようなコードにしています。（コードの全体は[notebook](https://www.kaggle.com/sishihara/python-kaggle-start-book-ch02-07)を見てもらえれば）
```
y_pred = (y_pred > 0.5).astype(int)
sub = pd.read_csv('../input/titanic/gender_submission.csv')
sub['Survived'] = y_pred
sub.to_csv('submission_lightgbm_holdout.csv', index=False)
```

> 全く同じscoreとなります。

全く同じscoreになるというのはどのような状況でしょうか？  

例えば、y_predがそれぞれの予測値になっていない。(何かの原因で、y_predが全部同じになってしまっているなど)    
サブミット時に正しくcsvファイルを選べていない。(notebookのOutputに複数のcsvファイルがある時は、サブミットするcsvファイルをクリックして反転させてから、サブミットする必要がある）  
など考えられますが、どうでしょうか。

**Comment by Muranikofu** [comment]
ご回答ありがとうございます。
submitファイルを作るコードを毎回以下のようにテンプレとしてコードを使い回しをしておりました。

sub = pd.read_csv('../input/titanic/gender_submission.csv')
sub['Survived'] = list(map(int, y_pred))
sub.to_csv('submission.csv'（適宜名前を変更）, index=False)

上記コードの2行目、sub['Survived'] = list(map(int, y_pred))をy_pred = (y_pred > 0.5).astype(int)と定義して、sub['Survived'] = y_predとすると、データが更新されて、scoreも変わりました。

また、全く同じscoreとは、改めて画像を添付させて頂きます。
<img width="950" alt="2020-08-09" src="https://user-images.githubusercontent.com/64767955/89723436-3ecb8780-da31-11ea-858b-62b743b7fc4b.png">

全く同じscroeとなる可能性として、ご指摘いただいた、「y_predがそれぞれの予測値になっていない。」ことが考えられます。

**Comment by upura** [comment]
予測値が0 or 1ではなく、0〜1の小数点の場合にも ` list(map(int, y_pred))` の処理を適用したことで、全ての値が切り捨てで0になっているのが原因ですね。下記のNotebookでスコアが再現しました。
https://www.kaggle.com/sishihara/kaggle-titanic-all-zero/output?scriptVersionId=40406197

既に @currypurin さんが回答済の通り `y_pred` の値に応じて提出用csv作成の処理を変える必要があります。具体的な処理については本書付属のサンプルコードや解説をご参照ください。

**Comment by Muranikofu** [comment]
upuraさん、curryourinさん

教えていただき、ありがとうございました。

今後も引き続き、学びを深めていきます。
