### ISSUE TITLE
P76 seedの意味

### ISSUE THREAD

**Issue by almark7032** [upura/python-kaggle-start-book#27]
P76の文中に登場する「乱数のseed」という言葉の意味が初見では分からず混乱しました。ググったらすぐ出てくる内容ではありましたが、個人的にはどこかで説明されていてもいいかなと感じました。

**Comment by upura** [comment]
#31 に登録いたしました。やり取りとしては完了している認識なので、closeいたします。フィードバックありがとうございました。
