### ISSUE TITLE
p.84 図2.39 の概要について

### ISSUE THREAD

**Issue by kyama0321** [upura/python-kaggle-start-book#33]
第2刷の p.84 図2.39の決定木内に，条件分岐に関する記述が無いことが気になりました．矢印が進むごとに，条件分岐の内容が最適化されていくことは容易に推測できますが，例を記入しておいていただけるとよりわかりやすくなるかなぁ...と思いました．
Issue立てるレベルの内容では無いかもしれませんが，ご参考になれば幸いです．

**Comment by upura** [comment]
ありがとうございます。どんな点でも、ご意見を頂けるのはありがたいです。次回以降加筆が可能なタイミングで、検討させていただきます。
