### ISSUE TITLE
p.86 48回目→38回目？

### ISSUE THREAD

**Issue by kyama0321** [upura/python-kaggle-start-book#34]
p.86 の以下の部分
> 今回は，39回目の学習以降，（中略）改善していません．そのため，48回目で学習が打ち切りとなっています．

"48回目" は誤植で，正しくは "38回目" ではないでしょうか．既にご指摘ありましたら，確認不十分ですみません．

**Comment by upura** [comment]
38回目の後、10回改善しなかった結果、early_stoppingで48回目で打ち切りになります。

**Comment by kyama0321** [comment]
なるほど、38+10=48なんですね。納得できました。ありがとうございます！
