### ISSUE TITLE
model.wv[' like ']について

### ISSUE THREAD

**Issue by almark7032** [upura/python-kaggle-start-book#35]
Word2vecのmodel.wv[' like ']（P135）をNotebookで実行したのですが、何度やり直してもこの部分だけいつまで経っても実行中のままで計算が終わりません。
この部分の処理は計算が重いのでしょうか？

**Comment by upura** [comment]
ご連絡ありがとうございます。README.mdにも記載しているKaggleのNotebookだと、それほど時間はかからないようです。
https://www.kaggle.com/sishihara/python-kaggle-start-book-ch03-03
