### ISSUE TITLE
リストの結合方向について

### ISSUE THREAD

**Issue by almark7032** [upura/python-kaggle-start-book#36]
私の理解が間違っているかもしれませんが、P164の真ん中あたりの、「trainとtestを一括で処理するために行方向に結合し」の部分は、列方向の間違いではないでしょうか？
リストを縦に繋いでるんですよね…？

**Comment by currypurin** [comment]
縦につないでいるというのは、認識の通りです。

行方向・列方向については、私は今回の言い回しのように使っておりました。
指摘頂いた点については今後の参考といたします。ありがとうございました。

**Comment by upura** [comment]
コメントありがとうございました。次回以降の改訂のタイミングで検討いたします。p.55にある「縦方向」という表現に揃えるのが良さそうですね。
