### ISSUE TITLE
pandas.Series = \について

### ISSUE THREAD

**Issue by almark7032** [upura/python-kaggle-start-book#37]
P165のサンプルコードに記載の
data['Embarked'] = \\
にはどういう役割があるのでしょうか？
Notebookの方には記載がありませんでしたが、あってもなくても同じなのでしょうか？

**Comment by upura** [comment]
バックスラッシュは、現在の行が次の行にも続いていることを意味します。
https://www.python.org/dev/peps/pep-3125/#terminal-in-the-general-case

p.165の紫色のボックス内に収めるため、Notebookとは異なり改行が必要となりました。紙幅の都合によるもので、実行結果に影響が出るものではありません。
