### ISSUE TITLE
p.92 Optuna インポート時のエラー

### ISSUE THREAD

**Issue by kyama0321** [upura/python-kaggle-start-book#39]
Kaggle 上に Notebook をコピーして，上から順に実行していましたが，p.82 のコード（Optunaを使う＠python-kaggle-start-book-ch02_06）実行時に，Optuna のインポート段階でエラーが生じてしまいました．
> AttributeError: type object '_yaml.Mark' has no attribute '__reduce_cython__'

Kaggle の環境によるものかなと思いコードの実行前に pip install optuna のコマンドを挿入＆実行したら，通るようになりました．
以上，簡単な報告です．

**Comment by upura** [comment]
コメントありがとうございます。差し支えなければ「Kaggle 上に Notebook をコピーして」の手順を具体的にご教示いただけますか？もしくはエラーが発生するNotebookをpublicにしてご共有いただけますか？

先ほど私が最新のKaggle Notebookの環境でch02_06のNotebook実行したところ、問題なくOptunaがインポートできました。
https://www.kaggle.com/sishihara/check-optuna-import-in-the-latest-env

**Comment by kyama0321** [comment]
> コメントありがとうございます。差し支えなければ「Kaggle 上に Notebook をコピーして」の手順を具体的にご教示いただけますか？
1. 書籍で示されている通り，以下のページから "Copy and Edit" しました．
https://www.kaggle.com/sishihara/python-kaggle-start-book-ch02-06
2. Notebook上で shift+return で上から順に実行していったところ，Optuna のところでエラーになってしまいました．実際のエラーメッセージはもっと長かったのですが，Attribute Errorの部分しかコピペのログに残ってませんでした...

＞もしくはエラーが発生するNotebookをpublicにしてご共有いただけますか？
pip install optuna した後はエラーがでなくなってしまいました．また， "Copy and Edit" し直して新規の Notebook で再現しようとしたのですが，上記のエラーは出ず．再現できなくてスミマセン...

**Comment by upura** [comment]
ご返信ありがとうございます。サンプルのKaggle Notebookから"Copy and Edit"した場合には、作成当時のDocker imageが使われるので、そちらの問題ではなさそうです。現在は再現しないとのことですが、類似の事例がないかは注視しておきます。ご報告ありがとうございました。
