### ISSUE TITLE
29ページのソースコードの実行

### ISSUE THREAD

**Issue by twaga** [upura/python-kaggle-start-book#45]
https://youtu.be/6B4NgqhFtUY

実行しても図１．１５にあるような3行の実行結果が全然出てきません。
何か足りない操作があるのでしょうか？

**Comment by upura** [comment]
こちらご返信遅くなり失礼いたしました。原因は、何も input にデータセットが追加されていない notebook で実行していることだと推察されます。以下のコンペティションのページから notebook を作成すると、input にデータセットが追加されているため、print の結果が出力されると期待されます。
https://www.kaggle.com/competitions/titanic/code
