### ISSUE TITLE
M1macの場合dockerのビルドが通らない件

### ISSUE THREAD

**Issue by yoshimi-I** [upura/python-kaggle-start-book#47]
こちらM1の場合ですとdockerのビルドが通らないので、そこを修正していただきたいです。
またこちらでdocker-composeの方にCPUを指定しましたが、それでもビルドができなかったのでもしよければM1用のファイルがあると助かります。

**Comment by upura** [comment]
ご連絡ありがとうございます。M1 mac は発刊当時に存在していなかったため、正式に対応するとなると影響範囲が大きく書籍全体の改変が必要となる可能性があります。一旦の対応としては Kaggle など、代替の環境をご利用いただければと考えております。M1 mac ユーザは一定数存在しているため #31 の課題に登録し、今後の対応を検討していきいます。
