### ISSUE TITLE
P27 - 「1.5.1 Notebookの作成」について

### ISSUE THREAD

**Issue by zizi4n5** [upura/python-kaggle-start-book#5]
```
Notebookを新たに作るには, Notebooksタブを選択した後、「New Notebook」をクリックします.
```

の箇所が文章だけだと少しわかりにくく、私の場合はトップページ左にある「Notebooks」を選択して「New Notebook」をクリックで進めてしまい、inputデータが空のNotebookが作成されて少しハマりました。
このため、以下のように画像もあるとわかりやすいと思いました。

---
Notebookを新たに作るには, Notebooksタブを選択した後,「New Notebook」をクリックします.
<img width="961" alt="Screen Shot 2020-03-20 at 17 10 19" src="https://user-images.githubusercontent.com/11887100/77146147-b8d49180-6acd-11ea-8ead-e6dea606d508.png">

**Comment by upura** [comment]
コメントありがとうございます。次回改定時の参考にさせていただきます。

**Comment by pokabu55** [comment]
私も、同じとところでハマりました。ここ見に来て、よかったです。
@zizi4n5  さん、ありがとうございます。

**Comment by upura** [comment]
#31 に登録いたしました。やり取りとしては完了している認識なので、closeいたします。フィードバックありがとうございました。
